services:
  api:
    build: ./api
    command: yarn develop
    environment:
      - "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}"
      - "GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}"
      - GITHUB_REDIRECT_URI=http://api.rhi.zone-development/auth/github/callback
      - WEBAPP_ORIGIN=http://rhi.zone-development
      - MYSQL_DATABASE=rhizone_lms_development
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=dev
      - MYSQL_USER=dev
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=rhizone_lms_development
      - MYSQL_PASSWORD=dev
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=dev
    image: mysql:8
    ports:
      - 3306:3306
  flyway:
    command: migrate
    depends_on:
      - db
    environment:
      - FLYWAY_CONNECT_RETRIES=10
      - FLYWAY_PASSWORD=dev
      - FLYWAY_URL=jdbc:mysql://db/rhizone_lms_development
      - FLYWAY_USER=dev
    image: flyway/flyway:8
    volumes:
      - ./db/migration:/flyway/sql
  nginx:
    depends_on:
      - api
      - webapp
    image: nginx:1
    ports:
      - 80:80
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/nginx.conf
  webapp:
    build: ./webapp
    command: yarn develop
    environment:
      - REACT_APP_API_ORIGIN=http://api.rhi.zone-development
    volumes:
      - ./webapp:/app
      - /app/node_modules
