CREATE TABLE options (
  id BIGINT NOT NULL AUTO_INCREMENT,
  label VARCHAR(255) NOT NULL,
  numeric_value INT NOT NULL DEFAULT(0),
  sort_order INT NOT NULL DEFAULT(0),
  prompt_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX options_prompt_id (prompt_id),
  FOREIGN KEY (prompt_id) REFERENCES prompts(id)
);