name: Bug Report
description: File a bug report for the Rhizone LMS.
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: Describe what you expect the code to do.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behaviour
      description: Describe what the code currently does.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: List steps that someone can perform to see the actual behaviour.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details and Resources
      description: Provide as much detail about this proposed change as you can, including links to lines of code, issues, PRs, and external resources where possible.
  - type: checkboxes
    attributes:
      label: Correct Project Selected
      description: Make sure to select the appropriate project for this bug report before submitting this issue.
      options:
        - label: This issue is linked to the appropriate project
          required: true
  - type: checkboxes
    attributes:
      label: Labels
      description: Make sure to select the appropriate labels for this bug report before submitting this issue.
      options:
        - label: This issue has appropriate labels.
          required: true
