blank_issues_enabled: false
contact_links:
  - name: Contact OpenTree Education
    url: https://opentree.education/contact
    about: For contact outside of our Discord, contact OpenTree Education through our website.
