name: Build and Push webapp

on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'

jobs:
  build_and_push_webapp:
    name: Build webapp image and push to registry
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}_webapp
          tags: |
            type=sha
            type=raw,value=latest
      - name: Build and push webapp image
        uses: docker/build-push-action@v2
        with:
          context: ./webapp/
          build-args: |
            REACT_APP_API_ORIGIN=https://api.rhi.zone
            REACT_APP_ROLLBAR_ACCESS_TOKEN=${{ secrets.ROLLBAR_CLIENT_ACCESS_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
