name: Check Code

on:
  pull_request:
    branches:
      - main

jobs:
  check_api:
    name: Lint and test api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ./api/yarn.lock
          node-version-file: ./api/.nvmrc
      - name: Install API dependencies
        if: always()
        run: yarn install
      - name: Check api formatting
        if: always()
        run: yarn prettier:check
      - name: Check api lint
        if: always()
        run: yarn eslint:check
      - name: Run api tests
        if: always()
        run: yarn test

  check_webapp:
    name: Lint and test webapp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ./webapp/yarn.lock
          node-version-file: ./webapp/.nvmrc
      - name: Install webapp dependencies
        if: always()
        run: yarn install
      - name: Check webapp formatting
        if: always()
        run: yarn prettier:check
      - name: Check webapp lint
        if: always()
        run: yarn eslint:check
      - name: Run webapp tests
        if: always()
        env:
          CI: true
        run: yarn test
