name: Check Code

on:
  pull_request:
    branches:
      - main

jobs:
  check_api:
    name: Lint and test api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ./api/yarn.lock
          node-version-file: ".nvmrc"
      - name: Install API dependencies
        if: always()
        working-directory: ./api/
        run: yarn install
      - name: Check api formatting
        if: always()
        working-directory: ./api/
        run: yarn prettier:check
      - name: Check api lint
        if: always()
        working-directory: ./api/
        run: yarn eslint:check
      - name: Run api tests
        if: always()
        working-directory: ./api/
        run: yarn test

  check_webapp:
    name: Lint and test webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ./webapp/yarn.lock
          node-version-file: ".nvmrc"
      - name: Install webapp dependencies
        if: always()
        working-directory: ./webapp/
        run: yarn install
      - name: Check webapp formatting
        if: always()
        working-directory: ./webapp/
        run: yarn prettier:check
      - name: Check webapp lint
        if: always()
        working-directory: ./webapp/
        run: yarn eslint:check
      - name: Run webapp tests
        if: always()
        working-directory: ./webapp/
        env:
          CI: true
        run: yarn test

  check_website:
    name: Lint website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
          node-version-file: ".nvmrc"
      - name: Install website dependencies
        if: always()
        working-directory: ./website/
        run: yarn install
      - name: Check website formatting
        if: always()
        working-directory: ./website/
        run: yarn prettier:check
      - name: Check website lint
        if: always()
        working-directory: ./website/
        run: yarn eslint:check
