name: Check Code

on:
  pull_request:
    branches:
      - main

jobs:
  all_checks:
    name: Lint and test packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
          cache-dependency-path: |
            api/yarn.lock
            webapp/yarn.lock

      - name: Install API dependencies
        if: always()
        working-directory: api
        run: yarn install
      - name: Check API formatting
        if: always()
        working-directory: api
        run: yarn prettier --check 'src/**/*.ts'
      - name: Check API lint
        if: always()
        working-directory: api
        run: yarn eslint 'src/**/*.ts'
      - name: Run API tests
        if: always()
        working-directory: api
        run: yarn jest --passWithNoTests

      - name: Install web app dependencies
        if: always()
        working-directory: webapp
        run: yarn install
      - name: Check web app formatting
        if: always()
        working-directory: webapp
        run: yarn prettier --check 'src/**/*.{ts,tsx,css}'
      - name: Check web app lint
        if: always()
        working-directory: webapp
        run: yarn eslint 'src/**/*.{ts,tsx}'
      - name: Run web app tests
        if: always()
        working-directory: webapp
        env:
          CI: true
        run: yarn test --passWithNoTests

      - name: Install website dependencies
        if: always()
        working-directory: website
        run: yarn install
      - name: Check website formatting
        if: always()
        working-directory: website
        run: yarn prettier --check 'src/**/*.{ts,tsx,css}'
      - name: Check website lint
        if: always()
        working-directory: website
        run: yarn eslint 'src/**/*.{ts,tsx}'
